services:
  database:
    image: postgres
    container_name: postgres_contracts
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=contracts
      - POSTGRES_DB=contracts
    volumes:
      - pgdata:/data/postgres
  app:
    build:
      context: .
      target: production
    container_name: contracts-management
    ports:
      - 3335:3333
    volumes:
      - .:/usr/app
    links:
      - database
    depends_on:
      - database
volumes:
  pgdata:
    driver: local
